### ISSUE TITLE
Seems not to work.

### ISSUE THREAD

**Issue by ThomasLeigh** [matej137/OutlookRemover#10]
First of all, **thank You for Your will to help with this sad and frustrating, disgusting issue from Microsoft.**

I've uninstalled New Outlook, I also have disabled Microsoft Store autoupdates, but still New Outlook returns :( . The script run as an administrator gives this (Windows 10 Home 22H2 64-bit.):

```
A subdirectory or file C:\Users\Thomas already exists.
Error occurred while processing: C:\Users\Thomas.
A subdirectory or file Leigh\AppData\Roaming\NewOutlook already exists.
Error occurred while processing: Leigh\AppData\Roaming\NewOutlook.
        1 file(s) copied.
Uninstalling the original version (reffer to readme for errors/red text)
installing the patched one (Errors are bad now)
Add-AppxPackage : A positional parameter cannot be found that accepts argument 'Leigh\AppData\Roaming\NewOutlook\AppxMa
nifest.xml'.
At line:1 char:1
+ add-appxpackage -register C:\Users\Thomas Leigh\AppData\Roaming\NewOu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-AppxPackage], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackag
   eCommand

Done!

```
I haven't found these subdirectories, though (incuding hidden files)...

Any chances to fix it?
```
```

**Comment by ThomasLeigh** [comment]
I'd like to add that [this](https://github.com/SempaiRock/OutlookRemover/releases/tag/1.0) does work succesfully in my case.

**Comment by eyesick2k7** [comment]
I got this error at first, but that was because I only unzipped the .batch file. You have to open the .bat file in the folder that it comes with. Basically unzip the entire folder and open it up in there. Hope this fixes your issue!

**Comment by ThomasLeigh** [comment]
@eyesick2k7 Thank You.

Unfortunately I've done that, meaning: I've launched the .bat file directly from the folder with three other files (AppxManifest.xml, AppxManifestx86.xml, Readme.txt)...

BTW, I've heard that Mail and Calendar apps won't be working in 2025 because they will be turned off on the server side... I don't understand this because I thought those apps don't need Microsoft servers as a necessary thing for them to run (for example, You could set up Google account for them).

I don't get it. Are those apps really so much dependent on Microsoft servers? I mean: I can use many apps for mail or calendar - even those apps which companies ceased to exist long time ago - but **I'm still able to use the apps**. So could someone explain me what's the difference here?

**Comment by matej137** [comment]
@ThomasLeigh 

Thank you for the information, I'll look into it tomorrow and report back when it is fixed

**Comment by matej137** [comment]
@ThomasLeigh
The issue should be fixed now, so thank you for your help with that. 

And about the Mail and calendar apps, what I believe Microsoft is talking about is that it will no longer work with Microsoft´s email services out of the box and you´ll have to set them up manually as a 3rd party IMAP/POP3 client. The same will probably happen with Gmail connection too at some point, as the app is no longer supported.
But I don´t really think that anything will happen to the app itsself. And even if, it would still be possible to downgrade to an older, working version

**Comment by ThomasLeigh** [comment]
@matej137 

Thank You very much! Your idea has been a huge positive gift for me, because I really don't like New Outlook, and also my Family - thanks to You They still are able to enjoy the experience of classic Mail and Calendar apps. It's incredible how brilliant the idea is under the hood :) .

> it would still be possible to downgrade to an older, working version

Would You be willing to tell how to downgrade those apps in case this would be needed? Do You mean that in such a case I should search for some repository with their older installation files?

**Comment by matej137** [comment]
Oh, I'm glad that you find this thing useful. 

And I'll probably add the option to install the older version of the app to the script if wanted in the near future, as (unlike the newer one) it does not nag you to switch

**Comment by ThomasLeigh** [comment]
> I'll probably add the option to install the older version of the app to the script if wanted in the near future, as (unlike the newer one) it does not nag you to switch

Oh, **it could be fantastic!** So far I just need to warn everybody to be careful no to accidentally click it.

**Comment by ThomasLeigh** [comment]
> I'll probably add the option to install the older version of the app to the script if wanted in the near future, as (unlike the newer one) it does not nag you to switch

Any chances for Outlook Remover with this functionality?
