### ISSUE TITLE
Still didn't work with a space in my user name

### ISSUE THREAD

**Issue by Suncoast-Cyclist** [matej137/OutlookRemover#12]
I was very grateful when I found OutlookRemover several weeks ago.  However, it seems that Microsoft is going to actively prevent the old Mail and Calendar app from continuing to work some time next year.  The first version of OutlookRemover I tried to use didn't leave a dummy entry in the installed apps list.  Maybe that was because it hadn't properly handled my user name which has a space in it.

I have two problems now.  I think I have a solution to the first one, but the second one is something I wasn't able to solve.

1. When I first ran the 0.99 version, it created a new directory in the directory where I had extracted OutlookRemover.zip which was named the last part of my user name.  It then copied the xml file as an untyped file to the base of my appdata folder.  Not surprisingly, the -register step didn't work until I added quotes around the name in the mkdir step.  When I ran the changed bat file, it did create the new directory in the proper place.
2. I then decided to remove OutlookRemover and was successfully able to use settings->apps->installed apps  to remove the dummy Outlook (new) app.  When I tried to install the real Outlook for Windows app, the Microsoft Store app gave me an unspecified error.  Could that problem be because I had previously used one of the earlier versions of OutlookRemover and it had appeared to work, although the xml file that it registered was in C:\Users.  Is there a possibility that the dummy Outlook from that previous -register step is still active?

**Comment by Suncoast-Cyclist** [comment]
Please disregard my 2nd issue. I was finally able to get around the error I was having when I tried to install the New Outlook from the Microsoft Store by running the wsreset command to reset the Microsoft Store.

**Comment by matej137** [comment]
Thank you, guess I overlooked that
