### ISSUE TITLE
file not found error when registering

### ISSUE THREAD

**Issue by MerrickZ** [matej137/OutlookRemover#2]
I don't know why but this line doesn't convert to the correct path:

"%systemdrive%\users\AppxManifest.xml"

![image](https://github.com/user-attachments/assets/446fccc2-971d-4cf7-8c9d-c30c5a4ac4c9)

then this script fails.

**Comment by matej137** [comment]
The issue appears to be caused by the fact that you are trying to run it in PowerShell. Please run it either by right clicking on the .bat file and clicking "run as administrator" or by running it from the command prompt (the black one)
