### ISSUE TITLE
Can you possibly support ARM64?

### ISSUE THREAD

**Issue by vt116** [matej137/OutlookRemover#3]
So far I have used this on 2/4 computers, however when I try it on my ARM64 Surface Pro X this issue comes up:

![Screenshot (1716)](https://github.com/user-attachments/assets/4c4b99ec-8394-4ab0-984a-df4d3317cc15)

If you can update the file to support ARM64, I would be grateful. Microsoft's frantic push for New Outlook is causing a lot of issues!

**Comment by matej137** [comment]
Thank you for the suggestion, I'll add it tomorrow/ on Friday

**Comment by matej137** [comment]
The support for ARM64 has been added in the latest release. I cannot verify if it actually works, so please let me know if it does not

**Comment by vt116** [comment]
Hi, I have tried it but unfortunately nothing happens :(

Would it be possible to re-try with the fork? I tried 0.9 with a normal computer before I tried the fork - your 0.9 version also seems to not be working for normal x64 systems, but SenpaiRock's fork is working.

**Comment by vt116** [comment]
@SempaiRock would it be at all possible to add ARM support to your fork?

**Comment by matej137** [comment]
Could you please go to settings > apps and check if outlook (new) is present with file size of around 8kb? If it is, the script is working

**Comment by vt116** [comment]
Hi,
Thanks for replying, I'm so glad some people are solving this.

I tried this with 0.95 and it doesn't work.

With @SempaiRock's version, the script opens up, slowly does its thing, then closes. With 0.95, the script only briefly pops up and closes and nothing happens.

**Comment by vt116** [comment]
Hi,
Thanks for replying, I'm so glad some people are solving this.

I tried this with 0.95 and it doesn't work.

With @SempaiRock's version, the script opens up, slowly does its thing, then closes. With 0.95, the script only briefly pops up and closes and nothing happens.

**Comment by vt116** [comment]
Hi,
I tried the manual uninstallation, then ran the script, and it works for ARM64! 
Thanks so much!

**Comment by matej137** [comment]
I´m glad that´s the case
