### ISSUE TITLE
Return to the old situation

### ISSUE THREAD

**Issue by ninoger** [matej137/OutlookRemover#5]
Hi, how can I go back to the old configuration? That is, is there a way to put the new Outlook back? Thank you

**Comment by onetoomanyonesandzeroes** [comment]
I too want to know this.

**Comment by imtipi** [comment]
+1 script broke my old outlook and only new outlook is working

**Comment by imtipi** [comment]
i tried
`reg delete "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /v AllowDevelopmentWithoutDevLicense /f`
in cmd
then
`Get-AppxPackage -allusers Microsoft.OutlookForWindows | Remove-AppxPackage -allusers`
in powershell(admin mode)
then I can use my old outlook as before

**Comment by onetoomanyonesandzeroes** [comment]
There are unintended consequences on my Windows 10 machine after doing this. 
How can I revert it please?

**Comment by onetoomanyonesandzeroes** [comment]
Thank you @imtipi. It worked.
I don't recommend doing this as the Mail app doesn't get notifications of new mail. 
It also messed with my browsers just by opening Mail.

**Comment by matej137** [comment]
You should be able to revert to the new outlook  by going to the settings app > apps > outlook (new) > uninstall and then installing the outlook (new) from the Microsoft store
